import type { Question } from "./questions";

type K = Question["kind"];
const q = (
  id: string,
  subject: string,
  kind: K,
  statement: string,
  options: string[],
  answer: number,
  explanation: string,
): Question => ({ id, subject, kind, statement, options, answer, explanation });

/** Nono lote de questões autorais inéditas, no estilo das provas. */
export const BATCH9_QUESTIONS: Record<string, Question[]> = {
  pmma: [
    q("pmma-t1", "Língua Portuguesa", "geral", "Assinale a alternativa em que a crase está corretamente empregada.", ["Vou à reunião do batalhão.", "Cheguei à casa cedo.", "Refiro-me à ele.", "Saí à uma hora."], 0, "Crase before feminine noun determined: \"à reunião\". Não há crase antes de pronome (\"a ele\") nem antes de palavra repetida (\"cara a cara\"); \"a uma hora\" não leva crase."),
    q("pmma-t2", "Língua Portuguesa", "geral", "Em \"O policial que agiu corretamente foi elogiado\", a oração destacada é:", ["Subordinada substantiva", "Subordinada adjetiva restritiva", "Subordinada adjetiva explicativa", "Coordenada conclusiva"], 1, "A oração \"que agiu corretamente\" funciona como adjetivo com valor restritivo (limita o antecedente), sem vírgulas."),
    q("pmma-t3", "Matemática", "geral", "Se 20% de um valor é R$ 240, o valor total é:", ["R$ 960", "R$ 1.100", "R$ 1.200", "R$ 2.400"], 2, "0,20 × X = 240 → X = 240 ÷ 0,20 = R$ 1.200."),
    q("pmma-t4", "Matemática", "geral", "Um jipe percorre 180 km em 2 horas e 30 minutos. Sua velocidade média é:", ["66 km/h", "70 km/h", "72 km/h", "80 km/h"], 2, "v = 180 ÷ 2,5 = 72 km/h."),
    q("pmma-t5", "Raciocínio Lógico", "geral", "A negação de \"todos os soldados são corajosos\" é:", ["Nenhum soldado é corajoso.", "Algum soldado não é corajoso.", "Todos os soldados são covardes.", "Alguns soldados são corajosos."], 1, "A negação de \"todo A é B\" é \"existe pelo menos um A que não é B\"."),
    q("pmma-t6", "Informática", "geral", "Uma cópia de dados mantida em local diferente do original, para recuperação após incidentes, chama-se:", ["Backup", "Cache", "Firewall", "Driver"], 0, "Backup é a cópia de segurança; firewall é proteção de rede; cache é memória temporária."),
    q("pmma-t7", "Informática", "geral", "No Excel, a fórmula =MÉDIA(4;8;12) retorna:", ["8", "12", "24", "Erro"], 0, "(4 + 8 + 12) ÷ 3 = 8."),
    q("pmma-t8", "Direito Constitucional", "especifica", "A casa é asilo inviolável, podendo nela entrar sem consentimento do morador:", ["Qualquer policial, a qualquer momento.", "Após determinação judicial, ou, em flagrante delito, desastre ou para prestar socorro.", "Somente de dia, em qualquer hipótese.", "Nunca, em nenhuma circunstância."], 1, "Art. 5º, XI da CF: determinação judicial ou, a qualquer hora, em flagrante, desastre ou socorro."),
    q("pmma-t9", "Direito Penal Militar", "especifica", "No Código Penal Militar, o crime de deserto ocorre quando o militar:", ["Chega atrasado à formatura.", "Se ausenta, sem licença, da unidade por mais de 8 dias.", "Dorme em serviço.", "Discute com o superior."], 1, "Art. 187 do CPM: ausência sem licença por mais de 8 dias configura deserção."),
    q("pmma-t10", "Legislação Estadual", "especifica", "A polícia judiciária e a apuração das infrações penais cabem, pela CF/88, às:", ["Polícias militares", "Polícias civis", "Guardas municipais", "Polícia federal exclusivamente no estado"], 1, "Art. 144, §4º da CF: às polícias civis cabem a polícia judiciária e a apuração das infrações penais."),
  ],
  cbmma: [
    q("cbmma-t1", "Língua Portuguesa", "geral", "Assinale a frase em que a concordância verbal está correta.", ["Fazem dois anos que ingressei.", "Faz dois anos que ingressei.", "Houveram muitos incêndios.", "Batem dez horas no relógio."], 1, "\"Fazer\" indicando tempo decorrido é impessoal: \"faz dois anos\". O mesmo vale para \"haver\" no sentido de existir."),
    q("cbmma-t2", "Língua Portuguesa", "geral", "A palavra \"mal\" (advérbio) tem como antônimo:", ["Mau", "Bem", "Bom", "Melhor"], 1, "\"Mal\" (advérbio) opõe-se a \"bem\"; \"mau\" (adjetivo) opõe-se a \"bom\"."),
    q("cbmma-t3", "Matemática", "geral", "Um tanque com 6.000 litros é esvaziado por uma bomba que retira 250 litros por minuto. O esvaziamento dura:", ["18 min", "24 min", "26 min", "32 min"], 1, "6.000 ÷ 250 = 24 minutos."),
    q("cbmma-t4", "Raciocínio Lógico", "geral", "Se \"todo bombeiro é corajoso\" e \"João é bombeiro\", conclui-se:", ["João é corajoso.", "João não é corajoso.", "Todo corajoso é bombeiro.", "Nada se pode concluir."], 0, "Silogismo válido: todo bombeiro é corajoso; João é bombeiro; logo, João é corajoso."),
    q("cbmma-t5", "Informática", "geral", "O software projetado para bloquear acessos não autorizados à rede de um quartel é o:", ["Antivírus", "Firewall", "Planilha", "Compactador"], 1, "O firewall filtra o tráfego e bloqueia acessos não autorizados."),
    q("cbmma-t6", "Combate a incêndio", "especifica", "Em incêndio de classe C (equipamentos elétricos energizados), o extintor indicado é o de:", ["Água pressurizada", "Espuma mecânica", "CO₂ ou pó químico", "Água nebulizada sobre o equipamento ligado"], 2, "Em equipamentos energizados, não se usa água ou espuma condutoras; CO₂ ou pó químico são adequados."),
    q("cbmma-t7", "Combate a incêndio", "especifica", "O triângulo do fogo é composto por:", ["Calor, luz e fumaça", "Combustível, comburente e calor", "Papel, madeira e plástico", "Chama, brasa e fumaça"], 1, "Os três elementos do triângulo do fogo: combustível, comburente (oxigênio) e calor."),
    q("cbmma-t8", "Primeiros socorros", "especifica", "Ao encontrar vítima inconsciente, o primeiro passo do atendimento é:", ["Oferecer água.", "Verificar a responsividade e a respiração.", "Colocá-la sentada.", "Tirar fotos do local."], 1, "Avaliar responsividade e respiração orienta a chamada de socorro e o início de manobras de suporte à vida."),
    q("cbmma-t9", "Salvamento e resgate", "especifica", "No afogamento, a conduta inicial em vítima resgatada consciente e respirando é:", ["Manter a vítima em repouso, aquecida e monitorada, aguardando o suporte avançado.", "Fazer compressões torácicas imediatas.", "Despejar água da vítima suspendendo-a pelos pés.", "Oferecer comida."], 0, "Vítima consciente e respirando: mantê-la em posição de conforto, aquecida e monitorada; compressões só em PCR."),
    q("cbmma-t10", "Defesa civil", "especifica", "A Defesa Civil tem como objetivo principal:", ["Julgar crimes comuns.", "Planejar e promover medidas de prevenção, mitigação, preparação, resposta e recuperação frente a desastres.", "Fiscalizar tributos estaduais.", "Controlar o trânsito urbano."], 1, "Defesa Civil articula ações de prevenção, mitigação, preparação, resposta e recuperação em situações de desastre."),
  ],
  tcema: [
    q("tcema-t1", "Língua Portuguesa", "geral", "Assinale a alternativa em que o plural está correto.", ["Cidadãos e cães", "Cidadães e cãos", "Cidadões e candos", "Cidadaos e caes"], 0, "\"Cidadão\" faz \"cidadãos\" e \"cão\" faz \"cães\" (palavras terminadas em -ão seguem mais de um padrão de plural)."),
    q("tcema-t2", "Raciocínio Lógico", "geral", "Se a proposição \"p → q\" é falsa, então necessariamente:", ["p e q são verdadeiras.", "p é verdadeira e q é falsa.", "p é falsa e q é verdadeira.", "p e q são falsas."], 1, "A condicional é falsa apenas quando V → F."),
    q("tcema-t3", "Informática", "geral", "No Excel, para somar os valores do intervalo A1 até A10, usa-se:", ["=SOMA(A1:A10)", "=SOMA(A1-A10)", "=TOTAL(A1;A10)", "=SOMAR(A1/A10)"], 0, "=SOMA(A1:A10) soma o intervalo; dois-pontos indica intervalo contínuo."),
    q("tcema-t4", "Matemática Financeira", "geral", "Aplicando R$ 1.000 a juros compostos de 10% ao ano, o montante após 2 anos é:", ["R$ 1.100", "R$ 1.200", "R$ 1.210", "R$ 1.220"], 2, "M = 1.000 × 1,1² = 1.000 × 1,21 = R$ 1.210."),
    q("tcema-t5", "Controle externo", "especifica", "Compete ao Tribunal de Contas do Estado, quanto à apreciação das contas:", ["Apenas registrar fatos, sem efeitos jurídicos.", "Julgar as contas dos administradores públicos e as gestões financeiras, apreciando as contas do Governador.", "Substituir o Legislativo na criação de leis orçamentárias.", "Aplicar sanções penais a gestores."], 1, "Art. 71 da CF (aplicável ao TCE por simetria): julgar as contas de administradores e a prestação do Governador, que aguarda 60 dias para apreciação da Assembleia."),
    q("tcema-t6", "Direito Administrativo", "especifica", "A licitação na modalidade em que a escolha ocorre por meio de cédula de compra ou lances, com sessão pública, é o:", ["Concorrência", "Pregão", "Concurso", "Leilão"], 1, "No pregão (Lei 14.133/2021), a disputa ocorre por meio de propostas e lances públicos; usado para bens e serviços comuns."),
    q("tcema-t7", "Direito Administrativo", "especifica", "O ato administrativo que declara a existência de direito ou situação prevista em lei, reconhecendo-o formalmente, é o ato:", ["Concedente", "Declaratório", "Atestatório", "Alienativo"], 1, "Atos declaratórios apenas reconhecem e declaram situação preexistente, sem criar direito novo."),
    q("tcema-t8", "Contabilidade Pública", "especifica", "A etapa da despesa pública que cria obrigação de pagamento para o Estado, reserva a dotação e garante ao credor o direito, é o:", ["Empenho", "Pagamento", "Liquidação", "Subvenção"], 0, "Art. 58 da Lei 4.320/64: empenho é o ato que cria para o Estado obrigação de pagamento pendente ou não de implemento de condição."),
    q("tcema-t9", "Direito Financeiro", "especifica", "Pela LRF, ao final de um bimestre, se a despesa total ultrapassar o limite, o ente deve:", ["Eliminar o excedente nos dois quadrimestres seguintes.", "Aumentar impostos imediatamente em qualquer hipótese.", "Ignorar o limite.", "Solicitar autorização ao TCE para exceder."], 0, "Art. 22, parágrafo único da LC 101/2000: eliminar o excedente nos dois quadrimestres seguintes, ao menos um terço no primeiro."),
    q("tcema-t10", "Orçamento público", "especifica", "A emenda ao projeto de lei orçamentária anual só pode ser aprovada caso seja compatível com o:", ["PPA e a LDO", "Regimento interno apenas", "Orçamento do ano anterior", "Programa de governo de partidos da oposição"], 0, "Art. 166, §3º da CF: emendas ao projeto de LOA exigem compatibilidade com o PPA e a LDO."),
  ],
  pcma: [
    q("pcma-t1", "Língua Portuguesa", "geral", "Assinale a alternativa em que a regência está correta.", ["Prefiro investigar a prender.", "Prefiro investigar do que prender.", "Prefiro mais investigar que prender.", "Prefiro a investigar."], 0, "\"Preferir\" é preferência exclusiva: \"prefiro X a Y\", sem \"mais\", \"do que\" ou preposição \"a\" repetida."),
    q("pcma-t2", "Língua Portuguesa", "geral", "Em \"Investigou-se o caso; provou-se o crime\", o pronome \"se\" é índice de indeterminação do sujeito em:", ["Investigou-se o caso, pois \"caso\" é o sujeito.", "Nenhuma das duas, pois ambas têm sujeito agente determinado.", "Provou-se o crime, pois \"crime\" é o sujeito.", "Ambas."], 1, "Com verbos transitivos diretos (investigar, provar), o \"se\" é partícula apassivadora e o objeto vira sujeito paciente, não índice de indeterminação."),
    q("pcma-t3", "Raciocínio Lógico", "geral", "A proposição \"é falso que o suspeito confessou e a testemunha mentiu\" equivale a:", ["O suspeito confessou e a testemunha mentiu.", "O suspeito não confessou ou a testemunha não mentiu.", "O suspeito não confessou e a testemunha não mentiu.", "Ou o suspeito confessou, ou a testemunha mentiu."], 1, "Negação de conjunção: ¬(p ∧ q) ≡ ¬p ∨ ¬q."),
    q("pcma-t4", "Direito Penal", "especifica", "No furto qualificado pela escala ou destreza, o agente:", ["Usa violência contra pessoa.", "Usa grave ameaça.", "Utiliza instrumento ou habilidade para subtrair sem violência à pessoa.", "Subtrai bem de valor irrisório."], 2, "Escala (invadir por instrumento/superando obstáculo) e destreza (habilidade para subtrair sem violência) são qualificadoras do art. 155, §4º do CP."),
    q("pcma-t5", "Direito Penal", "especifica", "A Lei 13.869/2019 (abuso de autoridade) tipifica como crime a condução de pessoa:", ["Para prestar depoimento voluntário na delegacia, com ciência dos direitos.", "Preso, sem observância das formalidades legais ou sem comunicação imediata ao juiz.", "Por mandado judicial regular.", "Flagrada cometendo crime."], 1, "Art. 6º da Lei de Abuso de Autoridade: condução sem observância das formalidades legais ou sem comunicação imediata à autoridade judiciária."),
    q("pcma-t6", "Processo Penal", "especifica", "Segundo o CPP, a prisão em flagrante deve ser comunicada ao juiz em até:", ["24 horas", "48 horas", "5 dias", "10 dias"], 0, "Art. 306 do CPP: a autoridade que realizar a prisão comunicará imediatamente ao juiz, em até 24 horas após a realização da prisão."),
    q("pcma-t7", "Processo Penal", "especifica", "A interceptação telefônica (escuta) para fins de investigação criminal exige:", ["Autorização policial.", "Autorização judicial, com indícios de autoria e justificada utilidade da prova.", "Apenas anuência do investigado.", "Autorização do Ministério Público isoladamente."], 1, "Art. 10 da Lei 9.296/1996 e art. 5º, XII da CF: só por ordem judicial, com indícios razoáveis e justificada utilidade."),
    q("pcma-t8", "Medicina Legal", "especifica", "As manchas cadavéricas de lividez (hipostáticas) são importantes na perícia porque:", ["Indicam a hora exata do óbito.", "Sua posição ajuda a inferir se o corpo foi movimentado após a morte.", "Provam a identidade do cadáver.", "Confirmam a causa da morte."], 1, "Manchas hipostáticas migram nas primeiras horas; sua fixação em posição diferente da encontrada sugere movimentação do corpo."),
    q("pcma-t9", "Criminologia", "especifica", "Na teoria da rotulação (labeling approach), o foco do estudo do desvio recai sobre:", ["A biologia do delinquente.", "O processo social pelo qual certos comportamentos e pessoas são definidos como desviantes.", "A estrutura econômica apenas.", "A genética da criminalidade."], 1, "Becker e Lemert: o desvio resulta da reação social e da etiquetação, não apenas do ato em si."),
    q("pcma-t10", "Legislação Especial", "especifica", "Pela Lei Maria da Penha (Lei 11.340/2006), a medida protetiva de urgência pode ser concedida:", ["Somente após audiência com o agressor.", "De ofício ou a requerimento, independentemente de audiência das partes e sem necessidade de representação penal prévia.", "Somente com representação criminal já oferecida.", "Apenas em flagrante."], 1, "Art. 19 da Lei 11.340/2006: concedidas em 48 horas, de ofício ou a requerimento, sem audiência das partes e independente de tipificação penal."),
  ],
};
