import type { Question } from "./questions";

type K = Question["kind"];
const q = (
  id: string,
  subject: string,
  kind: K,
  statement: string,
  options: string[],
  answer: number,
  explanation: string,
): Question => ({ id, subject, kind, statement, options, answer, explanation });

/** Quinto lote de questões autorais inéditas, no estilo das provas. */
export const BATCH5_QUESTIONS: Record<string, Question[]> = {
  pmma: [
    q("pmma-p1", "Língua Portuguesa", "geral", "Assinale a alternativa com concordância verbal correta.", ["Fazem dois anos que ingressei na corporação.", "Houveram muitas ocorrências no feriado.", "Faz dois anos que ingressei na corporação.", "Existe muitas viaturas paradas."], 2, "\"Fazer\" indicando tempo decorrido é impessoal e fica no singular. \"Haver\" (existir) também é impessoal; \"existir\" concorda com o sujeito (existem viaturas)."),
    q("pmma-p2", "Língua Portuguesa", "geral", "Em \"O sargento, que era experiente, orientou a tropa\", a oração entre vírgulas é:", ["Subordinada adjetiva explicativa.", "Subordinada adjetiva restritiva.", "Subordinada substantiva apositiva.", "Coordenada explicativa."], 0, "Oração introduzida por pronome relativo e isolada por vírgulas acrescenta informação ao antecedente: adjetiva explicativa."),
    q("pmma-p3", "Matemática", "geral", "Uma viatura percorre 240 km com 20 litros de combustível. Quantos litros gastará para percorrer 360 km?", ["25", "28", "30", "32"], 2, "Consumo de 12 km/L. 360 ÷ 12 = 30 litros."),
    q("pmma-p4", "Raciocínio Lógico", "geral", "A negação de \"Todo policial é disciplinado\" é:", ["Nenhum policial é disciplinado.", "Algum policial não é disciplinado.", "Todo policial é indisciplinado.", "Algum policial é disciplinado."], 1, "A negação de \"todo A é B\" é \"algum A não é B\"."),
    q("pmma-p5", "Informática", "geral", "No Windows, o atalho Ctrl + Z normalmente serve para:", ["Copiar", "Desfazer a última ação", "Recortar", "Selecionar tudo"], 1, "Ctrl+Z desfaz; Ctrl+C copia; Ctrl+X recorta; Ctrl+A seleciona tudo."),
    q("pmma-p6", "Direito Constitucional", "especifica", "Segundo a CF/88, as polícias militares são forças auxiliares e reserva:", ["Da Polícia Federal.", "Do Exército.", "Da Marinha.", "Da Força Nacional."], 1, "Art. 144, §6º: polícias militares e corpos de bombeiros militares são forças auxiliares e reserva do Exército."),
    q("pmma-p7", "Direito Constitucional", "especifica", "A casa é asilo inviolável, podendo-se nela entrar sem consentimento do morador, durante o dia, apenas:", ["Por ordem do delegado.", "Por determinação judicial, além de flagrante, desastre ou socorro.", "Por ordem do comandante do batalhão.", "Em nenhuma hipótese."], 1, "Art. 5º, XI: flagrante delito, desastre ou socorro a qualquer hora; por determinação judicial, somente durante o dia."),
    q("pmma-p8", "Direito Penal", "especifica", "Considera-se em legítima defesa quem, usando moderadamente dos meios necessários, repele:", ["Qualquer agressão passada.", "Injusta agressão, atual ou iminente, a direito seu ou de outrem.", "Perigo atual que não provocou por sua vontade.", "Ordem legal de superior."], 1, "Art. 25 do CP. O perigo atual não provocado caracteriza estado de necessidade (art. 24)."),
    q("pmma-p9", "Direitos Humanos", "especifica", "A Declaração Universal dos Direitos Humanos foi adotada pela ONU em:", ["1945", "1948", "1966", "1988"], 1, "A DUDH foi proclamada pela Assembleia Geral da ONU em 10 de dezembro de 1948."),
    q("pmma-p10", "Processo Penal", "especifica", "Segundo o CPP, considera-se em flagrante delito quem:", ["Foi apontado por testemunha dias depois.", "Está cometendo a infração penal ou acaba de cometê-la.", "Tem antecedentes criminais.", "Foi intimado a depor."], 1, "Art. 302, I e II do CPP, além das hipóteses de perseguição e de ser encontrado logo depois com objetos que façam presumir a autoria."),
  ],
  cbmma: [
    q("cbmma-p1", "Língua Portuguesa", "geral", "Assinale a palavra acentuada pela mesma regra de \"incêndio\".", ["Ônibus", "Histórico", "Série", "Café"], 2, "\"Incêndio\" e \"série\" são paroxítonas terminadas em ditongo crescente."),
    q("cbmma-p2", "Matemática", "geral", "Um reservatório de 12.000 litros está com 35% da capacidade. Quantos litros contém?", ["3.500", "4.200", "4.800", "7.800"], 1, "0,35 × 12.000 = 4.200 litros."),
    q("cbmma-p3", "Raciocínio Lógico", "geral", "Se \"chove, então o solo fica molhado\" é verdadeira e o solo não está molhado, conclui-se que:", ["Choveu.", "Não choveu.", "Pode ter chovido.", "O solo está seco por outro motivo e choveu."], 1, "Modus tollens: se P→Q e ¬Q, então ¬P."),
    q("cbmma-p4", "Atualidades", "geral", "A sigla COP, usada nas conferências climáticas da ONU, significa:", ["Conferência das Partes", "Comitê de Operações Planetárias", "Conselho de Proteção Ambiental", "Comissão Oceânica Permanente"], 0, "COP = Conference of the Parties (Conferência das Partes) da Convenção-Quadro sobre Mudança do Clima."),
    q("cbmma-p5", "Combate a incêndio", "especifica", "Os elementos do tetraedro do fogo são:", ["Combustível, comburente, calor e reação em cadeia.", "Combustível, água, calor e oxigênio.", "Oxigênio, nitrogênio, calor e fumaça.", "Calor, fumaça, chama e brasa."], 0, "O tetraedro acrescenta a reação em cadeia ao triângulo (combustível, comburente e calor)."),
    q("cbmma-p6", "Combate a incêndio", "especifica", "Incêndios em equipamentos elétricos energizados pertencem à classe:", ["A", "B", "C", "D"], 2, "Classe C: equipamentos energizados. A: sólidos; B: líquidos inflamáveis; D: metais pirofóricos."),
    q("cbmma-p7", "Combate a incêndio", "especifica", "O método de extinção que atua retirando o calor é o:", ["Abafamento", "Resfriamento", "Isolamento", "Quebra da reação em cadeia"], 1, "Resfriamento retira calor; abafamento retira o comburente; isolamento retira o combustível."),
    q("cbmma-p8", "Primeiros socorros", "especifica", "Na RCP em adulto, a frequência recomendada de compressões torácicas é de:", ["60 a 80 por minuto", "80 a 100 por minuto", "100 a 120 por minuto", "130 a 150 por minuto"], 2, "As diretrizes atuais recomendam 100 a 120 compressões por minuto, com profundidade de 5 a 6 cm."),
    q("cbmma-p9", "Primeiros socorros", "especifica", "Diante de hemorragia externa em membro, a primeira medida indicada é:", ["Aplicar gelo diretamente.", "Compressão direta sobre o ferimento.", "Oferecer água à vítima.", "Elevar a cabeça da vítima."], 1, "A compressão direta é a primeira conduta; o torniquete fica para sangramentos graves não controlados."),
    q("cbmma-p10", "Defesa civil", "especifica", "A Política Nacional de Proteção e Defesa Civil é instituída pela Lei:", ["8.112/1990", "12.608/2012", "9.605/1998", "13.425/2017"], 1, "A Lei 12.608/2012 institui a PNPDEC. A Lei 13.425/2017 (Lei Kiss) trata de prevenção de incêndios em estabelecimentos."),
  ],
  tcema: [
    q("tcema-p1", "Língua Portuguesa", "geral", "Assinale a alternativa em que a regência verbal está correta.", ["Assisti o jogo ontem.", "Prefiro estudar do que trabalhar.", "Aspiro ao cargo de técnico.", "Obedeça o regulamento."], 2, "\"Aspirar\" (desejar) exige \"a\". \"Assistir\" (ver) pede \"a\"; \"preferir\" usa \"a\" (prefiro X a Y); \"obedecer\" pede \"a\"."),
    q("tcema-p2", "Raciocínio Lógico", "geral", "Quantos anagramas tem a palavra CONTA?", ["60", "100", "120", "24"], 2, "Cinco letras distintas: 5! = 120."),
    q("tcema-p3", "Informática", "geral", "No Excel, a fórmula =SOMA(A1:A3) com A1=2, A2=5 e A3=8 resulta em:", ["10", "13", "15", "16"], 2, "2 + 5 + 8 = 15."),
    q("tcema-p4", "Matemática Financeira", "geral", "Um capital de R$ 2.000 aplicado a juros simples de 2% ao mês por 6 meses gera juros de:", ["R$ 120", "R$ 200", "R$ 240", "R$ 252"], 2, "J = C·i·t = 2.000 × 0,02 × 6 = R$ 240."),
    q("tcema-p5", "Controle externo", "especifica", "Segundo a CF/88, o controle externo é exercido pelo Poder Legislativo com o auxílio:", ["Do Ministério Público.", "Do Tribunal de Contas.", "Da Controladoria-Geral.", "Do Poder Judiciário."], 1, "Art. 71 da CF: o controle externo, a cargo do Congresso Nacional, é exercido com o auxílio do TCU; simetria aplicável aos Estados."),
    q("tcema-p6", "Direito Administrativo", "especifica", "O princípio que exige divulgação oficial dos atos administrativos é o da:", ["Moralidade", "Impessoalidade", "Publicidade", "Eficiência"], 2, "Publicidade (art. 37 da CF) garante transparência e início dos efeitos externos dos atos."),
    q("tcema-p7", "Direito Administrativo", "especifica", "A revogação de um ato administrativo ocorre por motivo de:", ["Ilegalidade.", "Conveniência e oportunidade.", "Decisão judicial obrigatória.", "Vício de forma."], 1, "Revogação: ato válido retirado por conveniência e oportunidade. Anulação: ilegalidade (Súmula 473 do STF)."),
    q("tcema-p8", "Orçamento público", "especifica", "O instrumento que estabelece diretrizes, objetivos e metas da administração para um período de quatro anos é:", ["LOA", "LDO", "PPA", "LRF"], 2, "O Plano Plurianual (art. 165, §1º, CF) é quadrienal."),
    q("tcema-p9", "Direito Financeiro", "especifica", "Pela LRF, o limite de despesa total com pessoal dos Estados é de:", ["50% da RCL", "54% da RCL", "60% da RCL", "49% da RCL"], 2, "Art. 19 da LC 101/2000: Estados e Municípios 60% da receita corrente líquida; União 50%."),
    q("tcema-p10", "Arquivologia", "especifica", "Os arquivos que guardam documentos de uso frequente pela administração são chamados de:", ["Permanentes", "Intermediários", "Correntes", "Históricos"], 2, "Pela teoria das três idades: corrente (uso frequente), intermediário e permanente (valor histórico)."),
  ],
  pcma: [
    q("pcma-p1", "Língua Portuguesa", "geral", "Assinale a alternativa em que a colocação pronominal segue a norma culta.", ["Me disseram a verdade.", "Não o encontrei na delegacia.", "Nunca viu-se tal crime.", "Quem avisou-te?"], 1, "Palavras negativas atraem o pronome (próclise). Não se inicia período com pronome oblíquo átono; \"nunca\" e \"quem\" também atraem."),
    q("pcma-p2", "Raciocínio Lógico", "geral", "A proposição \"p ∨ ¬p\" é classificada como:", ["Contradição", "Tautologia", "Contingência", "Falácia"], 1, "É sempre verdadeira, independentemente do valor de p: tautologia."),
    q("pcma-p3", "Informática", "geral", "Um programa que sequestra dados, criptografando-os e exigindo pagamento, é o:", ["Spyware", "Ransomware", "Adware", "Worm"], 1, "Ransomware cifra os dados e exige resgate."),
    q("pcma-p4", "Direito Penal", "especifica", "O crime de furto é caracterizado por:", ["Subtrair coisa alheia móvel mediante violência.", "Subtrair, para si ou para outrem, coisa alheia móvel, sem violência ou grave ameaça.", "Obter vantagem ilícita mediante fraude.", "Apropriar-se de coisa de que tem a posse."], 1, "Art. 155 do CP. Com violência ou grave ameaça é roubo (art. 157); fraude é estelionato; posse prévia é apropriação indébita."),
    q("pcma-p5", "Direito Penal", "especifica", "Ocorre crime tentado quando:", ["O agente desiste voluntariamente.", "Iniciada a execução, não se consuma por circunstâncias alheias à vontade do agente.", "O meio é absolutamente ineficaz.", "O agente se arrepende após a consumação."], 1, "Art. 14, II do CP. Meio absolutamente ineficaz caracteriza crime impossível (art. 17)."),
    q("pcma-p6", "Processo Penal", "especifica", "O inquérito policial é caracterizado como procedimento:", ["Judicial e contraditório.", "Administrativo, inquisitivo e dispensável.", "Obrigatório para toda ação penal.", "Público em todos os atos."], 1, "O IP é administrativo, inquisitivo, sigiloso e dispensável quando há elementos suficientes para a denúncia."),
    q("pcma-p7", "Processo Penal", "especifica", "A autoridade policial poderá mandar arquivar autos de inquérito?", ["Sim, sempre.", "Sim, se não houver indícios.", "Não, é vedado pelo CPP.", "Sim, com autorização do escrivão."], 2, "Art. 17 do CPP: a autoridade policial não poderá mandar arquivar autos de inquérito."),
    q("pcma-p8", "Medicina Legal", "especifica", "O instrumento que produz lesão perfurocortante é, por exemplo:", ["Martelo", "Faca de ponta", "Agulha", "Navalha"], 1, "Faca com ponta e gume perfura e corta. Agulha: perfurante; navalha: cortante; martelo: contundente."),
    q("pcma-p9", "Criminologia", "especifica", "A vitimologia estuda principalmente:", ["Apenas a pena.", "O papel da vítima no fenômeno criminal.", "A arquitetura prisional.", "O processo legislativo."], 1, "A vitimologia analisa a vítima, sua interação com o autor e os processos de vitimização."),
    q("pcma-p10", "Direitos Humanos", "especifica", "A Convenção Americana sobre Direitos Humanos também é conhecida como:", ["Pacto de São José da Costa Rica", "Carta de Paris", "Tratado de Viena", "Protocolo de Kyoto"], 0, "Assinada em 1969 em San José, Costa Rica, foi promulgada no Brasil pelo Decreto 678/1992."),
  ],
};
