import type { Question } from "./questions";

type K = Question["kind"];
const q = (
  id: string,
  subject: string,
  kind: K,
  statement: string,
  options: string[],
  answer: number,
  explanation: string,
): Question => ({ id, subject, kind, statement, options, answer, explanation });

/** Sexto lote de questões autorais inéditas, no estilo das provas. */
export const BATCH6_QUESTIONS: Record<string, Question[]> = {
  pmma: [
    q("pmma-q1", "Língua Portuguesa", "geral", "Assinale a alternativa em que o uso de \"porque\" está correto.", ["Não sei porque ele faltou.", "Ele faltou porque estava doente.", "Porque você não veio?", "Explique o porque da ausência."], 1, "\"Porque\" junto e sem acento é conjunção causal/explicativa. Em perguntas e com sentido de \"por qual motivo\": \"por que\"; substantivado: \"o porquê\"."),
    q("pmma-q2", "Língua Portuguesa", "geral", "O plural correto de \"cidadão\" é:", ["Cidadões", "Cidadães", "Cidadãos", "Cidadans"], 2, "\"Cidadão\" faz o plural em \"-ãos\": cidadãos."),
    q("pmma-q3", "Matemática", "geral", "Cinco policiais fazem uma ronda em 6 horas. Mantido o ritmo, quantas horas 3 policiais levariam?", ["3,6", "8", "10", "12"], 2, "Grandezas inversamente proporcionais: 5 × 6 = 3 × x → x = 10 horas."),
    q("pmma-q4", "Raciocínio Lógico", "geral", "Na sequência 2, 6, 18, 54, ..., o próximo termo é:", ["108", "148", "162", "216"], 2, "Progressão geométrica de razão 3: 54 × 3 = 162."),
    q("pmma-q5", "Informática", "geral", "O protocolo que indica uma conexão web criptografada é:", ["HTTP", "HTTPS", "FTP", "SMTP"], 1, "HTTPS usa TLS para cifrar a comunicação. FTP transfere arquivos; SMTP envia e-mails."),
    q("pmma-q6", "Direito Constitucional", "especifica", "É garantido o direito de reunião pacífica, sem armas, em locais abertos ao público:", ["Mediante autorização prévia da polícia.", "Independentemente de autorização, exigido prévio aviso à autoridade competente.", "Apenas com autorização judicial.", "Somente em horário comercial."], 1, "Art. 5º, XVI: não depende de autorização, mas exige aviso prévio e não pode frustrar outra reunião já convocada para o mesmo local."),
    q("pmma-q7", "Direito Penal", "especifica", "O crime de desacato consiste em:", ["Desobedecer ordem legal de funcionário público.", "Desacatar funcionário público no exercício da função ou em razão dela.", "Opor-se à execução de ato legal mediante violência.", "Solicitar vantagem indevida."], 1, "Art. 331 do CP. Desobediência é art. 330; resistência, art. 329; solicitar vantagem é corrupção passiva."),
    q("pmma-q8", "Direito Penal Militar", "especifica", "Abandonar, sem ordem superior, o posto ou lugar de serviço que lhe tenha sido designado configura, no CPM, o crime de:", ["Deserção", "Abandono de posto", "Insubordinação", "Motim"], 1, "Art. 195 do CPM. Deserção (art. 187) é ausentar-se da unidade por mais de oito dias."),
    q("pmma-q9", "Direitos Humanos", "especifica", "Pela Lei 13.869/2019, os crimes de abuso de autoridade exigem que o agente atue com finalidade específica de:", ["Apenas cumprir o dever legal.", "Prejudicar outrem, beneficiar a si ou a terceiro, ou por mero capricho ou satisfação pessoal.", "Obter promoção.", "Realizar a prisão em flagrante."], 1, "Art. 1º, §1º da Lei 13.869/2019 exige esse dolo específico; divergência na interpretação da lei não configura, por si só, abuso."),
    q("pmma-q10", "Legislação Estadual", "especifica", "A Polícia Militar do Maranhão, como instituição, subordina-se, nos termos da CF/88, ao:", ["Presidente da República.", "Governador do Estado.", "Ministro da Justiça.", "Comandante do Exército."], 1, "Art. 144, §6º da CF: polícias militares subordinam-se aos Governadores dos Estados."),
  ],
  cbmma: [
    q("cbmma-q1", "Língua Portuguesa", "geral", "Em \"Os bombeiros chegaram rapidamente\", a palavra \"rapidamente\" é:", ["Adjetivo", "Advérbio de modo", "Substantivo", "Preposição"], 1, "Indica o modo como a ação ocorreu: advérbio de modo."),
    q("cbmma-q2", "Matemática", "geral", "Uma mangueira enche um tanque em 4 horas e outra em 6 horas. Juntas, enchem em:", ["2 h", "2 h 24 min", "3 h", "5 h"], 1, "1/4 + 1/6 = 5/12 por hora; tempo = 12/5 h = 2,4 h = 2 h 24 min."),
    q("cbmma-q3", "Raciocínio Lógico", "geral", "A proposição \"Se há fumaça, então há fogo\" equivale a:", ["Se há fogo, então há fumaça.", "Se não há fogo, então não há fumaça.", "Se não há fumaça, então não há fogo.", "Há fumaça e não há fogo."], 1, "P→Q é equivalente à contrapositiva ¬Q→¬P."),
    q("cbmma-q4", "Informática", "geral", "Para enviar um e-mail ocultando os demais destinatários, usa-se o campo:", ["Para", "Cc", "Cco", "Assunto"], 2, "Cco (cópia carbono oculta) esconde os endereços dos outros destinatários."),
    q("cbmma-q5", "Combate a incêndio", "especifica", "O agente extintor indicado para incêndios de classe A é principalmente:", ["Água", "CO₂", "Pó para classe D", "Nenhum agente"], 0, "A água atua por resfriamento em materiais sólidos comuns (classe A)."),
    q("cbmma-q6", "Combate a incêndio", "especifica", "A forma de propagação do calor por meio de ondas eletromagnéticas, sem meio material, é a:", ["Condução", "Convecção", "Radiação", "Fricção"], 2, "Radiação: ondas eletromagnéticas. Condução: contato; convecção: movimento de fluidos aquecidos."),
    q("cbmma-q7", "Salvamento e resgate", "especifica", "Em salvamento aquático, o socorrista leigo deve preferencialmente:", ["Entrar na água imediatamente.", "Lançar objeto flutuante ou alcançar a vítima sem entrar na água.", "Esperar a vítima afundar.", "Retirar a roupa da vítima."], 1, "A sequência segura é: alcançar, lançar, e só entrar na água com treinamento e equipamento."),
    q("cbmma-q8", "Primeiros socorros", "especifica", "Em queimadura térmica recente, a conduta inicial adequada é:", ["Aplicar pasta de dente.", "Resfriar com água corrente em temperatura ambiente.", "Estourar as bolhas.", "Aplicar gelo direto."], 1, "Resfriar com água corrente por vários minutos; não usar gelo, cremes caseiros nem romper bolhas."),
    q("cbmma-q9", "Física aplicada", "especifica", "A pressão exercida por uma coluna de água aumenta com:", ["A diminuição da profundidade.", "O aumento da profundidade.", "A cor da água.", "A largura do recipiente."], 1, "Pela lei de Stevin, p = p₀ + d·g·h: cresce com a profundidade, independentemente da forma do recipiente."),
    q("cbmma-q10", "Legislação institucional", "especifica", "Segundo a CF/88, cabe aos corpos de bombeiros militares, além de outras atribuições legais:", ["A polícia judiciária.", "A execução de atividades de defesa civil.", "O policiamento ostensivo de trânsito federal.", "O controle externo da administração."], 1, "Art. 144, §5º da CF atribui aos corpos de bombeiros militares a execução de atividades de defesa civil."),
  ],
  tcema: [
    q("tcema-q1", "Língua Portuguesa", "geral", "Assinale a frase corretamente pontuada.", ["O relatório, foi entregue ontem.", "Os técnicos analisaram o processo e emitiram o parecer.", "Senhor, presidente a sessão começou.", "O auditor disse, que voltaria."], 1, "Não se separa sujeito de verbo nem verbo de complemento por vírgula; o vocativo deve ficar isolado inteiro (\"Senhor presidente,\")."),
    q("tcema-q2", "Raciocínio Lógico", "geral", "De quantas maneiras se escolhem 2 auditores entre 5 para uma comissão?", ["10", "20", "25", "5"], 0, "Combinação: C(5,2) = 5·4/2 = 10 (a ordem não importa)."),
    q("tcema-q3", "Informática", "geral", "No Excel, a referência que não muda ao copiar a fórmula é:", ["A1", "$A$1", "A$", "#A1"], 1, "O cifrão fixa coluna e linha: $A$1 é referência absoluta."),
    q("tcema-q4", "Matemática Financeira", "geral", "R$ 1.000 a juros compostos de 10% ao ano, por 2 anos, resultam em montante de:", ["R$ 1.100", "R$ 1.200", "R$ 1.210", "R$ 1.221"], 2, "M = 1.000 × 1,1² = R$ 1.210."),
    q("tcema-q5", "Controle externo", "especifica", "As decisões do Tribunal de Contas de que resulte imputação de débito ou multa têm eficácia de:", ["Mera recomendação.", "Título executivo.", "Sentença penal.", "Lei complementar."], 1, "Art. 71, §3º da CF: essas decisões terão eficácia de título executivo."),
    q("tcema-q6", "Controle externo", "especifica", "Compete ao Tribunal de Contas, quanto às contas anuais do Chefe do Poder Executivo:", ["Julgá-las definitivamente.", "Apreciá-las mediante parecer prévio.", "Arquivá-las.", "Aprová-las por decreto."], 1, "Art. 71, I: emite parecer prévio; o julgamento cabe ao Poder Legislativo."),
    q("tcema-q7", "Direito Administrativo", "especifica", "Pela Lei 14.133/2021, NÃO é modalidade de licitação:", ["Pregão", "Concorrência", "Diálogo competitivo", "Tomada de preços"], 3, "A nova lei prevê pregão, concorrência, concurso, leilão e diálogo competitivo; tomada de preços e convite foram extintas."),
    q("tcema-q8", "Direito Constitucional", "especifica", "A investidura em cargo efetivo depende de aprovação prévia em:", ["Entrevista.", "Concurso público de provas ou de provas e títulos.", "Indicação política.", "Análise curricular apenas."], 1, "Art. 37, II da CF, ressalvados os cargos em comissão de livre nomeação e exoneração."),
    q("tcema-q9", "Contabilidade Pública", "especifica", "Na despesa pública, o estágio que cria para o Estado obrigação de pagamento é o:", ["Empenho", "Liquidação", "Pagamento", "Fixação"], 0, "Art. 58 da Lei 4.320/64: o empenho cria a obrigação de pagamento, pendente ou não de condição."),
    q("tcema-q10", "Orçamento público", "especifica", "O princípio orçamentário segundo o qual a LOA não conterá dispositivo estranho à previsão da receita e fixação da despesa é o da:", ["Anualidade", "Exclusividade", "Universalidade", "Unidade"], 1, "Art. 165, §8º da CF (exclusividade), ressalvadas autorização para créditos suplementares e operações de crédito."),
  ],
  pcma: [
    q("pcma-q1", "Língua Portuguesa", "geral", "Em \"Os peritos analisaram as provas\", o termo \"as provas\" é:", ["Sujeito", "Objeto direto", "Objeto indireto", "Adjunto adverbial"], 1, "Complementa o verbo transitivo direto \"analisar\" sem preposição: objeto direto."),
    q("pcma-q2", "Raciocínio Lógico", "geral", "A negação de \"O suspeito fugiu e a vítima ficou ferida\" é:", ["O suspeito não fugiu e a vítima não ficou ferida.", "O suspeito não fugiu ou a vítima não ficou ferida.", "O suspeito fugiu ou a vítima ficou ferida.", "Se o suspeito fugiu, a vítima ficou ferida."], 1, "Lei de De Morgan: ¬(P ∧ Q) ≡ ¬P ∨ ¬Q."),
    q("pcma-q3", "Informática", "geral", "A técnica de enganar o usuário com mensagens falsas para obter senhas é chamada de:", ["Phishing", "Firewall", "Backup", "Cookie"], 0, "Phishing usa e-mails, sites ou mensagens fraudulentas para roubar dados."),
    q("pcma-q4", "Direito Penal", "especifica", "O crime de roubo se diferencia do furto principalmente pelo emprego de:", ["Fraude.", "Violência ou grave ameaça à pessoa.", "Repouso noturno.", "Coisa pública."], 1, "Art. 157 do CP: subtração mediante grave ameaça ou violência à pessoa."),
    q("pcma-q5", "Direito Penal", "especifica", "Quem, voluntariamente, desiste de prosseguir na execução responde:", ["Pela tentativa.", "Somente pelos atos já praticados.", "Pelo crime consumado.", "Por nenhum fato, em qualquer caso."], 1, "Art. 15 do CP (desistência voluntária): responde apenas pelos atos já praticados."),
    q("pcma-q6", "Processo Penal", "especifica", "Nos crimes de ação penal pública incondicionada, o inquérito policial será iniciado:", ["Somente por requerimento da vítima.", "De ofício pela autoridade policial ou mediante requisição.", "Apenas por ordem do juiz.", "Somente após a denúncia."], 1, "Art. 5º, I e II do CPP: de ofício ou mediante requisição da autoridade judiciária ou do MP, ou a requerimento do ofendido."),
    q("pcma-q7", "Processo Penal", "especifica", "O prazo para conclusão do inquérito de indiciado preso, regra geral do CPP, é de:", ["5 dias", "10 dias", "30 dias", "90 dias"], 1, "Art. 10 do CPP: 10 dias se preso; 30 dias se solto."),
    q("pcma-q8", "Medicina Legal", "especifica", "A rigidez cadavérica é um fenômeno cadavérico:", ["Abiótico consecutivo.", "Vital.", "Transformativo destrutivo.", "Conservador."], 0, "Rigidez, livores e resfriamento são fenômenos abióticos consecutivos; putrefação é transformativo destrutivo."),
    q("pcma-q9", "Legislação Estadual", "especifica", "A polícia civil, nos termos da CF/88, incumbe-se das funções de polícia judiciária e da apuração de infrações penais, exceto:", ["As de trânsito.", "As militares.", "As contra o patrimônio.", "As ambientais."], 1, "Art. 144, §4º: ressalvada a competência da União, exceto as infrações militares."),
    q("pcma-q10", "Direitos Humanos", "especifica", "Pela CF/88, a prática da tortura é crime:", ["Afiançável e prescritível.", "Inafiançável e insuscetível de graça ou anistia.", "Imprescritível e afiançável.", "Sujeito apenas a multa."], 1, "Art. 5º, XLIII: tortura, tráfico, terrorismo e hediondos são inafiançáveis e insuscetíveis de graça ou anistia."),
  ],
};
