import type { Question } from "./questions";

/** Terceiro lote de questões autorais inéditas, no estilo das provas, por matéria e concurso. */
export const MORE_QUESTIONS: Record<string, Question[]> = {
  pmma: [
    {
      id: "pmma-m1",
      subject: "Língua Portuguesa",
      kind: "geral",
      statement: "Assinale a alternativa em que a colocação pronominal está de acordo com a norma-padrão.",
      options: [
        "Nunca lhe disseram a verdade sobre o ocorrido.",
        "Me informaram que a viatura chegaria cedo.",
        "O sargento tinha se retirado-se da sala.",
        "Não devem preocupar-se-ão com o resultado.",
      ],
      answer: 0,
      explanation:
        "Palavra negativa (\"nunca\") atrai o pronome — próclise obrigatória. Não se inicia frase com pronome oblíquo, e as demais formas são agramaticais.",
    },
    {
      id: "pmma-m2",
      subject: "Língua Portuguesa",
      kind: "geral",
      statement: "Em \"O comandante elogiou os soldados, que agiram com coragem\", a palavra \"que\" é:",
      options: ["Conjunção integrante.", "Pronome relativo.", "Partícula expletiva.", "Advérbio de intensidade."],
      answer: 1,
      explanation: "\"Que\" retoma \"os soldados\" e introduz oração adjetiva: é pronome relativo.",
    },
    {
      id: "pmma-m3",
      subject: "Matemática",
      kind: "geral",
      statement: "Um pelotão de 36 soldados será dividido em grupos com o mesmo número de integrantes. Quantas divisões são possíveis com grupos de pelo menos 2 e no máximo 18 soldados?",
      options: ["5", "6", "7", "8"],
      answer: 2,
      explanation: "Divisores de 36 entre 2 e 18: 2, 3, 4, 6, 9, 12, 18 — sete opções.",
    },
    {
      id: "pmma-m4",
      subject: "Matemática",
      kind: "geral",
      statement: "Uma viatura consome 1 litro de combustível a cada 8 km. Para percorrer 360 km, com combustível a R$ 6,00 o litro, o gasto será de:",
      options: ["R$ 240,00", "R$ 270,00", "R$ 300,00", "R$ 320,00"],
      answer: 1,
      explanation: "360 ÷ 8 = 45 litros; 45 × 6 = R$ 270,00.",
    },
    {
      id: "pmma-m5",
      subject: "Raciocínio Lógico",
      kind: "geral",
      statement: "Considere: \"Se chove, então a ronda é adiada.\" Sabendo que a ronda não foi adiada, conclui-se corretamente que:",
      options: ["Choveu.", "Não choveu.", "A ronda foi cancelada.", "Nada se pode concluir."],
      answer: 1,
      explanation: "Modus tollens: negando o consequente (\"ronda adiada\"), nega-se o antecedente: não choveu.",
    },
    {
      id: "pmma-m6",
      subject: "Informática",
      kind: "geral",
      statement: "No navegador, a navegação anônima (ou privativa) tem como principal característica:",
      options: [
        "Ocultar o endereço IP do usuário na internet.",
        "Não salvar histórico, cookies e dados de formulários ao fechar a janela.",
        "Impedir que o provedor de internet registre os acessos.",
        "Bloquear todos os vírus e malwares.",
      ],
      answer: 1,
      explanation: "O modo anônimo evita registros locais (histórico, cookies), mas não oculta IP nem impede rastreamento pelo provedor.",
    },
    {
      id: "pmma-m7",
      subject: "Atualidades do Maranhão",
      kind: "geral",
      statement: "O rio que banha a cidade de Imperatriz e serve de divisa entre Maranhão e Tocantins é o:",
      options: ["Rio Itapecuru", "Rio Mearim", "Rio Tocantins", "Rio Parnaíba"],
      answer: 2,
      explanation: "Imperatriz fica à margem direita do rio Tocantins, divisa natural entre MA e TO. O Parnaíba separa MA do Piauí.",
    },
    {
      id: "pmma-m8",
      subject: "Direito Constitucional",
      kind: "especifica",
      statement: "São direitos sociais expressamente previstos no art. 6º da Constituição Federal, EXCETO:",
      options: ["Educação e saúde.", "Alimentação e moradia.", "Propriedade privada.", "Segurança e previdência social."],
      answer: 2,
      explanation: "Propriedade é direito individual (art. 5º). O art. 6º lista educação, saúde, alimentação, trabalho, moradia, transporte, lazer, segurança, previdência, proteção à maternidade e à infância e assistência aos desamparados.",
    },
    {
      id: "pmma-m9",
      subject: "Direito Constitucional",
      kind: "especifica",
      statement: "Ao militar dos Estados, conforme a Constituição Federal, é:",
      options: [
        "Permitida a sindicalização, vedada a greve.",
        "Vedada a sindicalização e a greve.",
        "Permitida a greve mediante aviso prévio.",
        "Permitida filiação partidária enquanto em serviço ativo.",
      ],
      answer: 1,
      explanation: "Art. 142, § 3º, IV, aplicável aos militares estaduais pelo art. 42, § 1º: são proibidas a sindicalização e a greve.",
    },
    {
      id: "pmma-m10",
      subject: "Direito Penal",
      kind: "especifica",
      statement: "Constitui causa excludente de ilicitude:",
      options: ["Coação moral irresistível.", "Erro de proibição inevitável.", "Estrito cumprimento do dever legal.", "Embriaguez completa fortuita."],
      answer: 2,
      explanation: "Art. 23 CP: estado de necessidade, legítima defesa, estrito cumprimento do dever legal e exercício regular de direito excluem a ilicitude. As demais excluem a culpabilidade.",
    },
    {
      id: "pmma-m11",
      subject: "Direito Penal",
      kind: "especifica",
      statement: "O crime de desacato (art. 331 do CP) consiste em:",
      options: [
        "Opor-se à execução de ato legal mediante violência.",
        "Desacatar funcionário público no exercício da função ou em razão dela.",
        "Ofender a honra de particular em local público.",
        "Deixar de cumprir ordem judicial.",
      ],
      answer: 1,
      explanation: "Desacato é humilhar/menosprezar funcionário público no exercício da função ou em razão dela. Resistência é o art. 329.",
    },
    {
      id: "pmma-m12",
      subject: "Legislação Institucional",
      kind: "especifica",
      statement: "No regime disciplinar militar, a transgressão disciplinar distingue-se do crime militar principalmente porque:",
      options: [
        "É julgada exclusivamente pela Justiça Militar.",
        "É infração de natureza administrativa, apurada e punida pela própria corporação.",
        "Sempre resulta em exclusão das fileiras.",
        "Depende de sentença penal condenatória.",
      ],
      answer: 1,
      explanation: "A transgressão é infração administrativa apurada em processo disciplinar interno; o crime militar é apurado pela Justiça Militar.",
    },
    {
      id: "pmma-m13",
      subject: "Direitos Humanos",
      kind: "especifica",
      statement: "A Declaração Universal dos Direitos Humanos (1948) estabelece, em seu art. 5º, que ninguém será submetido a:",
      options: [
        "Serviço militar obrigatório.",
        "Tortura nem a tratamento ou castigo cruel, desumano ou degradante.",
        "Prisão por dívida civil.",
        "Julgamento por tribunal de exceção.",
      ],
      answer: 1,
      explanation: "O art. 5º da DUDH veda a tortura e os tratamentos cruéis, desumanos ou degradantes.",
    },
    {
      id: "pmma-m14",
      subject: "Direitos Humanos",
      kind: "especifica",
      statement: "Segundo a Lei nº 13.869/2019 (abuso de autoridade), os crimes nela previstos exigem, para configuração, que o agente atue:",
      options: [
        "Com culpa, bastando a negligência.",
        "Com a finalidade específica de prejudicar outrem, beneficiar a si ou a terceiro, ou por mero capricho ou satisfação pessoal.",
        "Em qualquer hipótese de divergência na interpretação da lei.",
        "Somente fora do horário de serviço.",
      ],
      answer: 1,
      explanation: "Art. 1º, § 1º: exige dolo específico; a divergência na interpretação de lei ou na avaliação de fatos não configura abuso (§ 2º).",
    },
  ],
  cbmma: [
    {
      id: "cbmma-m1",
      subject: "Língua Portuguesa",
      kind: "geral",
      statement: "Assinale a alternativa em que o acento gráfico se justifica pela mesma regra de \"incêndio\".",
      options: ["Sótão", "Bombeiro", "Vítima", "Herói"],
      answer: 0,
      explanation: "\"Incêndio\" é paroxítona terminada em ditongo crescente (io), assim como \"sótão\" (ão). \"Vítima\" é proparoxítona; \"herói\" é oxítona com ditongo aberto.",
    },
    {
      id: "cbmma-m2",
      subject: "Língua Portuguesa",
      kind: "geral",
      statement: "Em \"A guarnição chegou rapidamente ao local\", o termo destacado \"rapidamente\" exerce a função de:",
      options: ["Adjunto adnominal.", "Adjunto adverbial de modo.", "Predicativo do sujeito.", "Complemento nominal."],
      answer: 1,
      explanation: "Advérbio de modo que modifica o verbo \"chegou\": adjunto adverbial de modo.",
    },
    {
      id: "cbmma-m3",
      subject: "Matemática",
      kind: "geral",
      statement: "Um reservatório cilíndrico tem raio de 2 m e altura de 5 m. Adotando π = 3, seu volume aproximado é:",
      options: ["30 m³", "45 m³", "60 m³", "75 m³"],
      answer: 2,
      explanation: "V = π·r²·h = 3 × 4 × 5 = 60 m³.",
    },
    {
      id: "cbmma-m4",
      subject: "Matemática",
      kind: "geral",
      statement: "Uma mangueira lança 200 litros de água por minuto. Em 3 horas e 15 minutos, o volume lançado é de:",
      options: ["36.000 L", "39.000 L", "42.000 L", "45.000 L"],
      answer: 1,
      explanation: "3 h 15 min = 195 min; 195 × 200 = 39.000 litros.",
    },
    {
      id: "cbmma-m5",
      subject: "Raciocínio Lógico",
      kind: "geral",
      statement: "Em um grupo de 40 bombeiros, 25 fazem curso de salvamento aquático e 22 fazem curso de combate a incêndio florestal; 10 fazem os dois. Quantos não fazem nenhum dos cursos?",
      options: ["1", "3", "5", "7"],
      answer: 1,
      explanation: "União = 25 + 22 − 10 = 37; 40 − 37 = 3 bombeiros.",
    },
    {
      id: "cbmma-m6",
      subject: "Informática",
      kind: "geral",
      statement: "No Microsoft Word, o atalho Ctrl + B (versão em português) executa a ação de:",
      options: ["Aplicar negrito.", "Salvar o documento.", "Abrir a caixa de busca.", "Inserir quebra de página."],
      answer: 1,
      explanation: "Na versão em português, Ctrl + B salva; negrito é Ctrl + N; localizar é Ctrl + L.",
    },
    {
      id: "cbmma-m7",
      subject: "Atualidades do Maranhão",
      kind: "geral",
      statement: "A festa popular maranhense que tem no \"Bumba Meu Boi\" sua principal manifestação ocorre tradicionalmente no período:",
      options: ["Carnavalesco", "Junino", "Natalino", "Da Semana Santa"],
      answer: 1,
      explanation: "O Bumba Meu Boi do Maranhão, Patrimônio Cultural da Humanidade (UNESCO, 2019), tem seu auge nas festas juninas.",
    },
    {
      id: "cbmma-m8",
      subject: "Prevenção e Combate a Incêndio",
      kind: "especifica",
      statement: "O extintor de pó químico seco (PQS) à base de bicarbonato de sódio é indicado principalmente para incêndios das classes:",
      options: ["A e B", "B e C", "A e D", "C e D"],
      answer: 1,
      explanation: "O PQS convencional (BC) age por abafamento e inibição da reação em cadeia, sendo indicado para líquidos inflamáveis (B) e equipamentos elétricos (C).",
    },
    {
      id: "cbmma-m9",
      subject: "Prevenção e Combate a Incêndio",
      kind: "especifica",
      statement: "A transmissão de calor que ocorre pelo deslocamento de massas de gases aquecidos, sendo a principal responsável pela propagação vertical do fogo em edificações, é a:",
      options: ["Condução", "Convecção", "Irradiação", "Combustão espontânea"],
      answer: 1,
      explanation: "Convecção: transferência pelo movimento de fluidos aquecidos (fumaça e gases sobem por escadas e shafts).",
    },
    {
      id: "cbmma-m10",
      subject: "Salvamento e Primeiros Socorros",
      kind: "especifica",
      statement: "Na reanimação cardiopulmonar (RCP) em adulto, realizada por socorrista leigo ou profissional, a relação entre compressões torácicas e ventilações recomendada é de:",
      options: ["15:2", "30:2", "5:1", "10:2"],
      answer: 1,
      explanation: "Diretrizes AHA: 30 compressões para 2 ventilações em adultos, com frequência de 100 a 120 compressões por minuto.",
    },
    {
      id: "cbmma-m11",
      subject: "Salvamento e Primeiros Socorros",
      kind: "especifica",
      statement: "Diante de uma hemorragia externa intensa em membro, a primeira conduta do socorrista deve ser:",
      options: [
        "Aplicar torniquete imediatamente acima da lesão.",
        "Realizar compressão direta sobre o ferimento.",
        "Elevar o membro e aguardar o SAMU.",
        "Lavar a ferida com água corrente.",
      ],
      answer: 1,
      explanation: "A compressão direta é a primeira medida; o torniquete é reservado a sangramentos incontroláveis em extremidades.",
    },
    {
      id: "cbmma-m12",
      subject: "Direito Constitucional",
      kind: "especifica",
      statement: "Além das atribuições definidas em lei, incumbe aos corpos de bombeiros militares, segundo a Constituição Federal:",
      options: ["A execução de atividades de defesa civil.", "A polícia judiciária militar.", "O policiamento ostensivo.", "A defesa das fronteiras."],
      answer: 0,
      explanation: "Art. 144, § 5º, parte final: aos CBMs incumbe, além das atribuições legais, a execução de atividades de defesa civil.",
    },
    {
      id: "cbmma-m13",
      subject: "Noções de Física Aplicada ao Incêndio",
      kind: "especifica",
      statement: "A menor temperatura na qual um combustível libera vapores em quantidade suficiente para inflamar-se momentaneamente ao contato com uma fonte de calor, sem manter a combustão, denomina-se ponto de:",
      options: ["Combustão", "Fulgor", "Ignição", "Ebulição"],
      answer: 1,
      explanation: "Ponto de fulgor: chama momentânea. Ponto de combustão: chama sustentada. Ponto de ignição: inflama-se sem fonte externa.",
    },
    {
      id: "cbmma-m14",
      subject: "Noções de Física Aplicada ao Incêndio",
      kind: "especifica",
      statement: "A água é o agente extintor mais utilizado principalmente porque atua por:",
      options: ["Inibição química da reação em cadeia.", "Resfriamento, devido ao seu alto calor específico e calor latente de vaporização.", "Retirada do material combustível.", "Diluição do oxigênio por reação química."],
      answer: 1,
      explanation: "A água absorve grande quantidade de calor ao aquecer e vaporizar, reduzindo a temperatura abaixo do ponto de combustão.",
    },
  ],
  tcema: [
    {
      id: "tcema-m1",
      subject: "Língua Portuguesa",
      kind: "geral",
      statement: "Assinale a alternativa em que o uso do pronome demonstrativo está correto quanto à referência espacial.",
      options: [
        "Esse documento aqui comigo é o original.",
        "Este relatório aqui na minha mesa precisa de assinatura.",
        "Aquele processo que você está segurando será arquivado.",
        "Este pedido que está lá no arquivo foi deferido.",
      ],
      answer: 1,
      explanation: "\"Este\" indica algo próximo de quem fala, por isso combina com \"aqui na minha mesa\". Usa-se \"esse\" para o que está perto do interlocutor e \"aquele\" para o que está longe de ambos.",
    },
    {
      id: "tcema-m2",
      subject: "Língua Portuguesa",
      kind: "geral",
      statement: "Na redação oficial, o fecho adequado para comunicações dirigidas a autoridades de hierarquia superior é:",
      options: ["Atenciosamente,", "Respeitosamente,", "Cordialmente,", "Saudações,"],
      answer: 1,
      explanation: "Manual de Redação da Presidência: \"Respeitosamente\" para autoridades superiores; \"Atenciosamente\" para mesma hierarquia ou inferior.",
    },
    {
      id: "tcema-m3",
      subject: "Raciocínio Lógico",
      kind: "geral",
      statement: "A proposição \"Não é verdade que o processo foi analisado e arquivado\" equivale logicamente a:",
      options: [
        "O processo não foi analisado e não foi arquivado.",
        "O processo não foi analisado ou não foi arquivado.",
        "O processo foi analisado ou foi arquivado.",
        "Se o processo foi analisado, então foi arquivado.",
      ],
      answer: 1,
      explanation: "Lei de De Morgan: ~(p ∧ q) ≡ ~p ∨ ~q.",
    },
    {
      id: "tcema-m4",
      subject: "Raciocínio Lógico",
      kind: "geral",
      statement: "De quantas maneiras distintas 5 servidores podem ser dispostos em fila para atendimento?",
      options: ["25", "60", "120", "240"],
      answer: 2,
      explanation: "Permutação simples: 5! = 120.",
    },
    {
      id: "tcema-m5",
      subject: "Informática",
      kind: "geral",
      statement: "No Excel, a fórmula =SE(A1>=7;\"Aprovado\";\"Reprovado\") retorna \"Aprovado\" quando:",
      options: ["A1 for menor que 7.", "A1 for maior ou igual a 7.", "A1 estiver vazia.", "A1 contiver texto."],
      answer: 1,
      explanation: "A função SE testa a condição A1>=7; se verdadeira, retorna o segundo argumento.",
    },
    {
      id: "tcema-m6",
      subject: "Informática",
      kind: "geral",
      statement: "Em segurança da informação, o princípio que garante que a informação não foi alterada indevidamente é o da:",
      options: ["Confidencialidade", "Integridade", "Disponibilidade", "Autenticidade"],
      answer: 1,
      explanation: "Integridade = informação íntegra e não alterada. Confidencialidade = acesso restrito; disponibilidade = acesso quando necessário.",
    },
    {
      id: "tcema-m7",
      subject: "Atualidades do Maranhão",
      kind: "geral",
      statement: "O movimento popular maranhense do século XIX (1838–1841), de caráter social e político, ocorrido no interior da província, ficou conhecido como:",
      options: ["Cabanagem", "Balaiada", "Sabinada", "Farroupilha"],
      answer: 1,
      explanation: "A Balaiada foi a revolta maranhense liderada por Manuel Balaio, Cosme Bento e Raimundo Gomes.",
    },
    {
      id: "tcema-m8",
      subject: "Direito Constitucional",
      kind: "especifica",
      statement: "As decisões do Tribunal de Contas de que resulte imputação de débito ou multa terão eficácia de:",
      options: ["Sentença judicial transitada em julgado.", "Título executivo.", "Ato normativo.", "Recomendação administrativa."],
      answer: 1,
      explanation: "Art. 71, § 3º, CF: as decisões do Tribunal de que resulte imputação de débito ou multa terão eficácia de título executivo.",
    },
    {
      id: "tcema-m9",
      subject: "Direito Constitucional",
      kind: "especifica",
      statement: "Nos termos do art. 37 da CF, a investidura em cargo ou emprego público depende de aprovação prévia em concurso público, ressalvadas:",
      options: ["As nomeações para cargo em comissão declarado em lei de livre nomeação e exoneração.", "As contratações de parentes até o terceiro grau.", "As funções gratificadas exercidas por terceirizados.", "As nomeações para cargos efetivos de nível superior."],
      answer: 0,
      explanation: "Art. 37, II, CF: exceção para cargos em comissão de livre nomeação e exoneração.",
    },
    {
      id: "tcema-m10",
      subject: "Administração Pública",
      kind: "especifica",
      statement: "O poder da Administração de rever seus próprios atos, anulando os ilegais e revogando os inconvenientes, decorre do princípio da:",
      options: ["Autotutela", "Impessoalidade", "Motivação", "Segurança jurídica"],
      answer: 0,
      explanation: "Súmula 473 do STF consagra a autotutela administrativa.",
    },
    {
      id: "tcema-m11",
      subject: "Controle Externo",
      kind: "especifica",
      statement: "Compete ao Tribunal de Contas, quanto às contas prestadas anualmente pelo Governador do Estado:",
      options: ["Julgá-las definitivamente.", "Apreciá-las mediante parecer prévio.", "Arquivá-las sem análise.", "Encaminhá-las ao Poder Judiciário."],
      answer: 1,
      explanation: "Por simetria ao art. 71, I, CF: o TC aprecia as contas do chefe do Executivo mediante parecer prévio; o julgamento cabe ao Legislativo.",
    },
    {
      id: "tcema-m12",
      subject: "Controle Externo",
      kind: "especifica",
      statement: "A prestação de contas é obrigação de:",
      options: [
        "Somente dos ordenadores de despesa dos órgãos do Executivo.",
        "Qualquer pessoa física ou jurídica, pública ou privada, que utilize, arrecade, guarde, gerencie ou administre dinheiros, bens e valores públicos.",
        "Apenas das empresas públicas e sociedades de economia mista.",
        "Exclusivamente dos agentes políticos.",
      ],
      answer: 1,
      explanation: "Art. 70, parágrafo único, CF.",
    },
    {
      id: "tcema-m13",
      subject: "Direito Administrativo",
      kind: "especifica",
      statement: "Segundo a Lei nº 14.133/2021, a modalidade de licitação obrigatória para aquisição de bens e serviços comuns é:",
      options: ["Concorrência", "Pregão", "Leilão", "Diálogo competitivo"],
      answer: 1,
      explanation: "Art. 6º, XLI, e art. 29 da Lei 14.133/2021: pregão é obrigatório para bens e serviços comuns.",
    },
    {
      id: "tcema-m14",
      subject: "Direito Administrativo",
      kind: "especifica",
      statement: "O atributo do ato administrativo que permite à Administração executá-lo diretamente, sem necessidade de prévia autorização judicial, é a:",
      options: ["Presunção de legitimidade", "Imperatividade", "Autoexecutoriedade", "Tipicidade"],
      answer: 2,
      explanation: "Autoexecutoriedade: execução direta pela Administração, nos casos previstos em lei ou em situações de urgência.",
    },
  ],
  pcma: [
    {
      id: "pcma-m1",
      subject: "Língua Portuguesa",
      kind: "geral",
      statement: "Assinale a alternativa em que há erro de concordância nominal.",
      options: [
        "Seguem anexos os documentos solicitados.",
        "É proibida a entrada de pessoas estranhas.",
        "Ela mesma redigiu o boletim de ocorrência.",
        "Os investigadores estavam meio cansados; a delegada, meia preocupada.",
      ],
      answer: 3,
      explanation: "\"Meio\" no sentido de \"um pouco\" é advérbio e invariável: \"meio preocupada\".",
    },
    {
      id: "pcma-m2",
      subject: "Língua Portuguesa",
      kind: "geral",
      statement: "Em \"Embora as provas fossem frágeis, o inquérito foi concluído\", a oração destacada expressa ideia de:",
      options: ["Causa", "Concessão", "Condição", "Consequência"],
      answer: 1,
      explanation: "\"Embora\" introduz oração subordinada adverbial concessiva.",
    },
    {
      id: "pcma-m3",
      subject: "Raciocínio Lógico",
      kind: "geral",
      statement: "Numa delegacia, cada investigador cumprimentou todos os outros com um aperto de mão, num total de 45 apertos. Quantos investigadores havia?",
      options: ["9", "10", "11", "12"],
      answer: 1,
      explanation: "C(n,2) = 45 ⇒ n(n−1)/2 = 45 ⇒ n = 10.",
    },
    {
      id: "pcma-m4",
      subject: "Raciocínio Lógico",
      kind: "geral",
      statement: "A proposição \"Se o suspeito confessou, então será indiciado\" é equivalente a:",
      options: [
        "Se o suspeito será indiciado, então confessou.",
        "Se o suspeito não será indiciado, então não confessou.",
        "O suspeito confessou e não será indiciado.",
        "O suspeito não confessou ou não será indiciado.",
      ],
      answer: 1,
      explanation: "Contrapositiva: p → q ≡ ~q → ~p.",
    },
    {
      id: "pcma-m5",
      subject: "Informática",
      kind: "geral",
      statement: "A técnica em que o criminoso envia mensagens falsas se passando por instituições confiáveis para obter dados pessoais é chamada de:",
      options: ["Phishing", "Sniffing", "Spoofing de IP", "Defacement"],
      answer: 0,
      explanation: "Phishing: engenharia social por e-mail/mensagem para capturar credenciais e dados.",
    },
    {
      id: "pcma-m6",
      subject: "Informática",
      kind: "geral",
      statement: "Em computação em nuvem, o modelo em que o usuário acessa aplicativos prontos pela internet, sem gerenciar a infraestrutura, é o:",
      options: ["IaaS", "PaaS", "SaaS", "DaaS"],
      answer: 2,
      explanation: "SaaS (Software as a Service): aplicação pronta para uso, como e-mail web ou suíte de escritório online.",
    },
    {
      id: "pcma-m7",
      subject: "Atualidades do Maranhão",
      kind: "geral",
      statement: "O Centro de Lançamento de Alcântara, importante para o programa espacial brasileiro, está localizado:",
      options: ["No litoral norte do Maranhão, próximo a São Luís.", "No sul do Maranhão, em Balsas.", "Na fronteira com o Pará, em Imperatriz.", "No leste maranhense, em Caxias."],
      answer: 0,
      explanation: "Alcântara fica na Baía de São Marcos, em frente a São Luís, e sua posição próxima à linha do Equador favorece lançamentos.",
    },
    {
      id: "pcma-m8",
      subject: "Direito Constitucional",
      kind: "especifica",
      statement: "Segundo a Constituição Federal, a casa é asilo inviolável do indivíduo, nela podendo-se penetrar sem consentimento do morador:",
      options: [
        "A qualquer hora, mediante determinação do delegado.",
        "Em caso de flagrante delito ou desastre, ou para prestar socorro, ou, durante o dia, por determinação judicial.",
        "Somente durante o dia, em qualquer hipótese.",
        "Apenas com mandado judicial, a qualquer hora.",
      ],
      answer: 1,
      explanation: "Art. 5º, XI, CF.",
    },
    {
      id: "pcma-m9",
      subject: "Direito Constitucional",
      kind: "especifica",
      statement: "A prisão de qualquer pessoa e o local onde se encontre serão comunicados imediatamente:",
      options: ["Ao Ministério Público e à Defensoria.", "Ao juiz competente e à família do preso ou à pessoa por ele indicada.", "Ao delegado-geral apenas.", "À Ordem dos Advogados do Brasil."],
      answer: 1,
      explanation: "Art. 5º, LXII, CF.",
    },
    {
      id: "pcma-m10",
      subject: "Direito Penal",
      kind: "especifica",
      statement: "O furto qualifica-se, entre outras hipóteses, quando cometido:",
      options: ["Durante o repouso noturno.", "Com destruição ou rompimento de obstáculo à subtração da coisa.", "Por agente primário sobre coisa de pequeno valor.", "Com violência ou grave ameaça à pessoa."],
      answer: 1,
      explanation: "Art. 155, § 4º, I, CP. Repouso noturno é causa de aumento (§ 1º); violência/grave ameaça caracteriza roubo.",
    },
    {
      id: "pcma-m11",
      subject: "Direito Penal",
      kind: "especifica",
      statement: "Quanto ao concurso de pessoas, adota-se no Código Penal, como regra, a teoria:",
      options: ["Pluralista", "Dualista", "Monista (unitária)", "Da acessoriedade máxima"],
      answer: 2,
      explanation: "Art. 29 CP: quem concorre para o crime incide nas penas a este cominadas, na medida de sua culpabilidade — teoria monista.",
    },
    {
      id: "pcma-m12",
      subject: "Direito Processual Penal",
      kind: "especifica",
      statement: "Considera-se em flagrante delito quem:",
      options: [
        "É encontrado, 30 dias após o crime, com objetos que façam presumir a autoria.",
        "É perseguido, logo após, pela autoridade, pelo ofendido ou por qualquer pessoa, em situação que faça presumir ser autor da infração.",
        "Confessa espontaneamente o crime na delegacia.",
        "É denunciado anonimamente como autor de crime.",
      ],
      answer: 1,
      explanation: "Art. 302, III, CPP (flagrante impróprio ou quase-flagrante).",
    },
    {
      id: "pcma-m13",
      subject: "Direito Processual Penal",
      kind: "especifica",
      statement: "O prazo para conclusão do inquérito policial, no procedimento comum, quando o indiciado estiver preso, é de:",
      options: ["5 dias", "10 dias", "15 dias", "30 dias"],
      answer: 1,
      explanation: "Art. 10 CPP: 10 dias se preso; 30 dias se solto (prorrogáveis).",
    },
    {
      id: "pcma-m14",
      subject: "Criminologia",
      kind: "especifica",
      statement: "A teoria criminológica que explica o crime pela aprendizagem de valores e técnicas em grupos íntimos é a da:",
      options: ["Anomia (Merton)", "Associação diferencial (Sutherland)", "Etiquetamento (labeling approach)", "Escola Positiva (Lombroso)"],
      answer: 1,
      explanation: "Sutherland: o comportamento criminoso é aprendido na interação com grupos íntimos.",
    },
    {
      id: "pcma-m15",
      subject: "Criminologia",
      kind: "especifica",
      statement: "A prevenção criminal que atua sobre grupos de risco, antes da ocorrência do delito, é classificada como prevenção:",
      options: ["Primária", "Secundária", "Terciária", "Reativa"],
      answer: 1,
      explanation: "Primária: causas sociais gerais; secundária: grupos de risco; terciária: reincidência do condenado.",
    },
  ],
};
